dashboard_overview = {
    "totalBrokers": 20,
    "activeProjects": 16,
    "pendingTasks": 8,
    "overdueTasks": 3,
    "highRiskCount": 5,
    "summary": "当前重点是处理本周升级节点、条件单包逾期和环境未就绪问题。",
}

dashboard_projects = [
    {
        "id": 1,
        "brokerName": "A券商",
        "projectName": "4月20日版本升级",
        "projectType": "版本升级",
        "ownerName": "张三",
        "plannedDate": "2026-04-20",
        "progressPercent": 75,
        "riskCount": 2,
        "overdueCount": 1,
        "status": "执行中",
    },
    {
        "id": 2,
        "brokerName": "B券商",
        "projectName": "接口改造",
        "projectType": "接口改造",
        "ownerName": "李四",
        "plannedDate": "2026-04-18",
        "progressPercent": 40,
        "riskCount": 1,
        "overdueCount": 0,
        "status": "准备中",
    },
    {
        "id": 3,
        "brokerName": "C券商",
        "projectName": "新接入项目",
        "projectType": "常规对接",
        "ownerName": "王五",
        "plannedDate": "2026-04-24",
        "progressPercent": 55,
        "riskCount": 2,
        "overdueCount": 0,
        "status": "执行中",
    },
]

brokers = [
    {
        "id": 1,
        "name": "A券商",
        "shortName": "A券商",
        "currentProjects": 3,
        "activeProjects": 2,
        "nextMilestone": "4/20 版本升级",
        "riskCount": 2,
        "overdueCount": 1,
    },
    {
        "id": 2,
        "name": "B券商",
        "shortName": "B券商",
        "currentProjects": 2,
        "activeProjects": 1,
        "nextMilestone": "4/18 接口改造",
        "riskCount": 1,
        "overdueCount": 0,
    },
    {
        "id": 3,
        "name": "C券商",
        "shortName": "C券商",
        "currentProjects": 4,
        "activeProjects": 3,
        "nextMilestone": "4/24 首轮验证",
        "riskCount": 2,
        "overdueCount": 0,
    },
]

project_detail = {
    "id": 1,
    "brokerName": "A券商",
    "name": "2026-04-20 版本升级",
    "projectType": "版本升级",
    "ownerName": "张三",
    "plannedDate": "2026-04-20",
    "status": "执行中",
    "progressPercent": 75,
    "overdueCount": 1,
    "description": "涉及后台程序包、接口包、条件单包交付与验证，当前最大风险点为条件单包交付延迟。",
    "tasks": [
        {
            "id": 11,
            "name": "后台程序包",
            "ownerName": "张三",
            "plannedContent": "提供程序包",
            "plannedDate": "2026-04-15",
            "actualAction": "已提交",
            "completionResult": "完成",
            "status": "已完成",
        },
        {
            "id": 12,
            "name": "接口包",
            "ownerName": "李四",
            "plannedContent": "提供接口包",
            "plannedDate": "2026-04-16",
            "actualAction": "联调中",
            "completionResult": "进行中",
            "status": "进行中",
        },
        {
            "id": 13,
            "name": "条件单包",
            "ownerName": "王五",
            "plannedContent": "提供条件单包",
            "plannedDate": "2026-04-14",
            "actualAction": "未提交",
            "completionResult": "未完成",
            "status": "已逾期",
        },
    ],
    "risks": [
        {
            "id": 21,
            "title": "接口验证延迟",
            "level": "高风险",
            "affectsMilestone": True,
            "ownerName": "李四",
            "plannedResolveDate": "2026-04-17",
            "status": "处理中",
            "actionPlan": "增加联调窗口，确保 4/17 前完成验证。",
        },
        {
            "id": 22,
            "title": "对方环境未就绪",
            "level": "中风险",
            "affectsMilestone": False,
            "ownerName": "张三",
            "plannedResolveDate": "2026-04-18",
            "status": "持续关注",
            "actionPlan": "提前确认窗口，必要时拆分验证计划。",
        },
    ],
    "logs": [
        {
            "id": 31,
            "logDate": "2026-04-13 09:30",
            "content": "接口包已开始第二轮联调",
            "nextAction": "今晚确认联调结果，必要时明早补窗口。",
        },
        {
            "id": 32,
            "logDate": "2026-04-13 10:20",
            "content": "条件单包仍未收到，已提醒负责人",
            "nextAction": "在风险中心继续跟进并视情况调整计划。",
        },
    ],
}

reminders = [
    {
        "id": 1,
        "type": "逾期",
        "brokerName": "A券商",
        "projectName": "4月20日版本升级",
        "itemName": "条件单包",
        "level": "高风险",
        "deadline": "2026-04-14",
        "status": "待处理",
        "description": "仍未提交，已影响升级准备。",
    },
    {
        "id": 2,
        "type": "临期",
        "brokerName": "B券商",
        "projectName": "接口改造",
        "itemName": "接口验证",
        "level": "中风险",
        "deadline": "2026-04-15",
        "status": "处理中",
        "description": "距离计划时间还有 2 天，当前仍在联调。",
    },
    {
        "id": 3,
        "type": "高风险",
        "brokerName": "C券商",
        "projectName": "新接入项目",
        "itemName": "环境未提供",
        "level": "高风险",
        "deadline": "2026-04-16",
        "status": "待处理",
        "description": "影响首轮验证，需要本周协调对方开放环境。",
    },
]

templates = [
    {
        "id": 1,
        "name": "版本升级模板",
        "templateType": "升级",
        "scene": "版本升级、投产、上线准备",
        "taskCount": 8,
        "riskCount": 4,
        "recentUseCount": 10,
    },
    {
        "id": 2,
        "name": "接口改造模板",
        "templateType": "改造",
        "scene": "接口联调、协议调整、改造验证",
        "taskCount": 6,
        "riskCount": 3,
        "recentUseCount": 5,
    },
    {
        "id": 3,
        "name": "常规对接模板",
        "templateType": "对接",
        "scene": "常规需求接入、资料准备、例行事项",
        "taskCount": 7,
        "riskCount": 2,
        "recentUseCount": 3,
    },
]

weekly_report = {
    "summary": "本周共推进 16 个项目，其中 4 个关键节点项目进入执行阶段，3 个事项触发临期或逾期预警。",
    "completed": [
        "A券商后台程序包已交付。",
        "B券商接口联调完成第一轮。",
        "D券商上线前验证计划已确认。",
    ],
    "nextWeek": [
        "推进 A券商条件单包交付并完成升级窗口确认。",
        "完成 C券商环境确认并安排首轮验证。",
        "补齐 E券商常规对接模板任务配置。",
    ],
    "overdue": [
        "A券商条件单包已逾期 1 天。",
        "F券商验证反馈待回收已超过计划时间。",
    ],
    "risks": [
        "C券商环境未就绪，影响关键节点。",
        "D券商上线窗口未确认，排期存在不确定性。",
    ],
    "coordination": [
        "协调对方尽快确认升级窗口。",
        "确认接口联调失败后的备用验证安排。",
    ],
}
